server:
  port: 3000
spring:
  application:
    name: crowd-redis
  redis:
    host: 192.168.88.132
    password: 123456 #redis的密码
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

