server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  routes:
    crowd-portal:
      service-id: crowd-auth #微服务名称
      path: /** # 可以访问多级目录 不然的话静态资源无法加载 因为静态资源在多级目录下
    crowd-project:
      service-id: crowd-project
      path: /project/** #映射规则不可以重复
    crowd-order:
      service-id: crowd-order
      path: /order/**
    crowd-pay:
      service-id: crowd-pay
      path: /pay/**
  ignored-services: "*"
  sensitive-headers: "*" # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头）
spring:
  application:
    name: crowd-zuul
  redis:
    host: 192.168.88.132
    password: 123456
  session:
    store-type: redis
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000