server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: provider1 # 路由id，建议配合服务名,没有固定规则，要求唯一
            #uri: http://localhost:1000 #匹配提供服务的路由地址
          uri: lb://provider1 #lb：负载均衡
          predicates:
            - Path=/provider/**
              # 断言，路径相匹配的进行路由
              # 如果不配置 spring.cloud.gateway.discovery.locator.enabled=true 那么这个断言地址必须符合请求地址的前缀
              #拼接后  http://localhost:1000 + /provider/**
      discovery:
        locator:
          enabled: true #开启之后我们就可以通过地址去访问服务了，格式如下：
                        # http://网关地址/服务名称（大写）/**
                        # http://localhost:9527/PROVIDER1/provider/get/emp/list/remote?keyword=1
          lower-case-service-id: true
          # 开启后 http://网关地址/服务名称（小写）/** 此时大写服务名称不能访问
          # http://localhost:9527/provider1/provider/get/emp/list/remote?keyword=1
